export const ACTIONS = {
	"CARS_LOAD":"CARS_LOAD",
	"CARS_LOAD_ERROR":"CARS_LOAD_ERROR",
	"CARS_SET":"CARS_SET",
	"ORDERS_LOAD":"ORDERS_LOAD",
	"ORDERS_LOAD_ERROR":"ORDERS_LOAD_ERROR",
	"ORDERS_SET":"ORDERS_SET",
	"ORDER_REMOVE":"ORDER_REMOVE",
	"SET_CURRENT_CAR":"SET_CURRENT_CAR",
	"ADD_GOODS":"ADD_GOODS",
	"ACTIONS.ADD_ORDERS_FROM_CAR":"ACTIONS.ADD_ORDERS_FROM_CAR"
}
